services:
  - type: web
    name: abhaya-ml
    runtime: python
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 1 -b 0.0.0.0:5000 app:app"
    plan: free
    envVars:
      - key: FIREBASE_CREDENTIALS_PATH
        sync: false
      - key: FIREBASE_DB_URL
        sync: false
